-- tcgscan-michi-maker — local seed data
--
-- Run automatically by `supabase db reset`. There is intentionally nothing to seed:
--
--   * Reference data (pokemon, illustrators, sets, cards) is NOT part of this project — it
--     lives in the shared tcgscan-data server and is consumed over HTTP (docs/DATA-SERVER.md).
--   * User data (profiles, binders, pages, slots) is created through the app so that
--     auth.uid() / RLS apply; seeding it here would bypass ownership.
--
-- Kept as a placeholder so `supabase db reset` has a seed file to run.
