/**
 * Content module: the two 30th-anniversary example binders.
 *
 * Generated by `scripts/build-anniversary-binders.mjs` from the live card pool, and attributed to
 * @michimaker like every content module (see `src/data/sampleData.ts`).
 *
 * What makes these two worth their place in the examples section is the PAIRING pages, which show
 * something no other example does: a pocket pair that says the same card twice. "Thirty Years,
 * Thirty Cards" seats each Classic Collection reprint beside the print it came from, which works
 * because that set keeps every card's original collector number. "Pikachu, By Many Hands" does the
 * within-set version: the ordinary print beside its Special Illustration Rare.
 *
 * To regenerate (after a card list changes, or to re-pick the pairs): edit the config at the top of
 * the builder, run `node scripts/build-anniversary-binders.mjs`, commit the JSON. The builder
 * refuses to guess an original print it cannot pin down, so a failed build means a pair needs
 * choosing by hand, not a looser matcher.
 */
import anniversary from '@/data/anniversaryBinders.json';
import type { ContentModule, DemoBinder } from '@/data/content/_helpers';

export const cards: ContentModule['cards'] = [];

export const binders: ContentModule['binders'] = anniversary as unknown as DemoBinder[];
