/**
 * Content module: the 30th-anniversary story binder.
 *
 * Generated by `scripts/build-anniversary-binders.mjs` from the live card pool, and attributed to
 * @michimaker like every content module (see `src/data/sampleData.ts`).
 *
 * ONE binder across BOTH anniversary sets, thirty pages, because the two are one story told from
 * both ends: the Celebration is thirty years of artists drawing the same Pokemon, the Classic
 * Collection is thirty years of the cards themselves. It replaced a first attempt that split them
 * into two four-page binders, which made each half look thinner than it is and put the rhymes
 * between them on different shelves.
 *
 * It is also the fullest michi-method example that ships: fifty-four artwork panels across thirty
 * pages, spent on the Special Illustration Rares and Illustration Rares whose whole point is a
 * picture with no card furniture on it, with ordinary prints carrying the trainer, mechanic and
 * history pages where the story is what changed rather than what is beautiful.
 *
 * To regenerate (after a card list changes, or to re-cut a page): edit PAGES at the top of the
 * builder, run `node scripts/build-anniversary-binders.mjs`, commit the JSON. The builder refuses
 * to write a binder it cannot verify: a collector number that has left the set, a card used twice
 * on one page, or a slot that spills past its page all fail the build rather than producing a
 * binder with a hole in it.
 */
import anniversary from '@/data/anniversaryBinders.json';
import type { ContentModule, DemoBinder } from '@/data/content/_helpers';

export const cards: ContentModule['cards'] = [];

export const binders: ContentModule['binders'] = anniversary as unknown as DemoBinder[];
