/**
 * THE PRESET SLEEVES AND ART BACKINGS, re-hosted by us.
 *
 * A sleeve or a backing is stored in the same text column as a colour and told apart by shape: an
 * http(s) URL is a picture, #rrggbb is a colour (src/data/pageStyle.ts, isImageRef). These are the
 * pictures on offer, so that choosing a texture is a tap rather than finding an address and pasting
 * it, and so that a preset cannot break because somebody else's server moved.
 *
 * EVERY URL IS IN OUR OWN BUCKET and content-addressed, so it is stable forever and a re-run of the
 * script that made it changes nothing. Generated by scripts/presets/rehost-surfaces.mjs; the
 * credits are kept because these came from Pixabay photographers, whose licence does not require
 * attribution but whose work is still theirs.
 */

export interface SurfacePreset {
  id: string;
  label: string;
  url: string;
  /** Who made the picture, and where it came from. Shown wherever there is room for it. */
  credit: { author: string; source: 'Pixabay'; sourceUrl: string };
}

export const SURFACE_PRESETS: readonly SurfacePreset[] = [
  {
    id: 'holo-rainbow',
    label: 'Rainbow holo',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-holo-rainbow-d516c35da82c7ed4.jpg',
    credit: { author: 'Alexas_Fotos', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/bubble-soap-bubble-sphere-3594979/' },
  },
  {
    id: 'gold-foil',
    label: 'Gold foil',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-gold-foil-2f7d214125434b27.jpg',
    credit: { author: 'analogicus', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/gold-gold-leaf-metal-foil-metal-6969821/' },
  },
  {
    id: 'silver-foil',
    label: 'Silver foil',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-silver-foil-c92cfd7a9b290295.jpg',
    credit: { author: 'analogicus', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/aluminum-foil-crumpled-foil-aluminum-6969822/' },
  },
  {
    id: 'carbon-black',
    label: 'Carbon black',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-carbon-black-55a68bdaaef332d9.jpg',
    credit: { author: 'CreaPark', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/carbon-foil-automotive-car-wrap-2797211/' },
  },
  {
    id: 'marble-white',
    label: 'White marble',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-marble-white-5c145ecdd92fcc9e.jpg',
    credit: { author: 'North_Studio', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/marble-texture-white-pattern-2362265/' },
  },
  {
    id: 'velvet-dark',
    label: 'Dark velvet',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-velvet-dark-64c4fc2f0ea29daa.jpg',
    credit: { author: 'Engin_Akyurt', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/fabric-abstract-texture-2446476/' },
  },
  {
    id: 'linen-cream',
    label: 'Cream linen',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-linen-cream-4e58982c2a105f68.jpg',
    credit: { author: 'virin000', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/textile-jute-brown-fabric-texture-2918844/' },
  },
  {
    id: 'kraft-paper',
    label: 'Kraft paper',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-kraft-paper-77128736f313bf3a.jpg',
    credit: { author: 'ulotkidruk', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/paper-brown-texture-background-1468883/' },
  },
  {
    id: 'galaxy-deep',
    label: 'Deep galaxy',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-galaxy-deep-61b179eb173d505c.jpg',
    credit: { author: 'WikiImages', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/space-universe-night-sky-sky-fog-11099/' },
  },
  {
    id: 'dew-violet',
    label: 'Violet dew',
    url: 'https://piikwvntldytjejxmcla.supabase.co/storage/v1/object/public/binder-art/29a6e25c-c5a0-4c2a-9a5b-62c98e288605/surface-dew-violet-1e45b9d36b972e80.jpg',
    credit: { author: 'Leohoho', source: 'Pixabay', sourceUrl: 'https://pixabay.com/photos/water-drops-gradient-background-6373296/' },
  },
];

/** A preset by id, or undefined. Ids are stable; the URL behind one may be re-hosted. */
export function surfacePreset(id: string): SurfacePreset | undefined {
  return SURFACE_PRESETS.find((p) => p.id === id);
}

/** The preset a stored value corresponds to, when it is one of ours rather than a typed address. */
export function presetForUrl(url: string | null | undefined): SurfacePreset | undefined {
  return url ? SURFACE_PRESETS.find((p) => p.url === url) : undefined;
}
