/**
 * Generates SPEC.md, the audit spec sheet, from the suites themselves.
 *
 * THE SHEET IS GENERATED, NEVER HAND WRITTEN, because a hand-written spec drifts from the checks
 * within a month and then quietly becomes fiction. If a row is in the sheet, a check produces it; if
 * a check exists, it is in the sheet. `rig spec` is committed output, so a diff on it shows exactly
 * what coverage a change added or removed.
 */
import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import { SUITES } from './suites/index.mjs';
import { PERSONAS } from './lib/personas.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const COLUMNS = ['guest', 'free', 'pro-trial'];

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

function cell(check, persona) {
  if (!check.personas.includes(persona)) {
    const p = PERSONAS[persona];
    return p && !p.available ? '_phase 2_' : '-';
  }
  const v = check.expect[persona] ?? check.expect['*'];
  return v ? esc(v) : '?';
}

export function writeSpec() {
  const lines = [];
  const total = SUITES.reduce((n, s) => n + s.checks.length, 0);

  lines.push('# Audit spec sheet');
  lines.push('');
  lines.push('Generated by `node qa/rig.mjs spec`. Do not hand edit: a spec that drifts from the checks becomes fiction within a month.');
  lines.push('');
  lines.push(`${total} checks across ${SUITES.length} areas.`);
  lines.push('');
  lines.push('## How to read a row');
  lines.push('');
  lines.push('- **proves** is what the row protects, in plain words. If a row fails and you cannot tell why it mattered, that field is the bug.');
  lines.push('- **A dash** in a tier column means the check makes no claim at that tier. An empty column is a coverage hole and is meant to be visible.');
  lines.push('- **pro-trial** holds `tier_pro` and `tcgscan_pro`, the same products a paid PRO holds, so every PRO gate resolves identically. There is no `pro` or `vip` column: a paid tier needs a live charge or the management token, and the trial is close enough (owner, 2026-09-21).');
  lines.push('- **unreachable** is an expectation, not a skip. The check FAILS if the thing turns out to be reachable.');
  lines.push('- **danger** is what the check writes. The console sums it into a write budget above the Run button.');
  lines.push('');

  lines.push('## Coverage at a glance');
  lines.push('');
  lines.push(`| area | checks | ${COLUMNS.join(' | ')} |`);
  lines.push(`| --- | --- | ${COLUMNS.map(() => '---').join(' | ')} |`);
  for (const suite of SUITES) {
    const per = COLUMNS.map((p) => suite.checks.filter((c) => c.personas.includes(p)).length);
    lines.push(`| ${suite.area} | ${suite.checks.length} | ${per.join(' | ')} |`);
  }
  lines.push('');

  for (const suite of SUITES) {
    lines.push(`## ${suite.label}`);
    lines.push('');
    lines.push(suite.blurb);
    lines.push('');
    for (const check of suite.checks) {
      lines.push(`### \`${check.id}\``);
      lines.push('');
      lines.push(`**${esc(check.title)}**`);
      lines.push('');
      lines.push(esc(check.proves));
      lines.push('');
      lines.push(`| surface | severity | danger | observed by |`);
      lines.push(`| --- | --- | --- | --- |`);
      lines.push(`| ${esc(check.surface)} | ${check.severity || 'major'} | ${check.danger} | ${(check.observe || []).join(', ')} |`);
      lines.push('');
      lines.push(`| ${COLUMNS.join(' | ')} |`);
      lines.push(`| ${COLUMNS.map(() => '---').join(' | ')} |`);
      lines.push(`| ${COLUMNS.map((p) => cell(check, p)).join(' | ')} |`);
      lines.push('');
      lines.push(`source: ${[].concat(check.source).map((s) => `\`${s}\``).join(', ')}`);
      lines.push('');
    }
  }

  const path = join(HERE, 'SPEC.md');
  writeFileSync(path, lines.join('\n'));

  const json = SUITES.flatMap((s) =>
    s.checks.map((c) => ({
      id: c.id, area: c.area, app: c.app, title: c.title, proves: c.proves, surface: c.surface,
      danger: c.danger, severity: c.severity || 'major', personas: c.personas, expect: c.expect,
      observe: c.observe, source: [].concat(c.source), heavy: Boolean(c.heavy), targets: c.targets || ['prod', 'export'],
    })),
  );
  writeFileSync(join(HERE, 'spec.json'), JSON.stringify(json, null, 2));
  return path;
}
